server:
    port: 8080

spring:
    datasource:
      url: ${DB_URL}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          format_sql: true
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
              scope:
                - openid
                - profile
                - email
              redirect-uri: http://localhost:8080/login/oauth2/code/google
              authorization-grant-type: authorization_code
              client-name: Google
            facebook:
              clientId: ${FACEBOOK_CLIENT_ID}
              clientSecret: ${FACEBOOK_CLIENT_SECRET}
              scope:
                - openid
                - email
                - public_profile
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
              user-name-attribute: sub
    data:
      redis:
        host: ${REDIS_HOST:localhost}
        port: ${REDIS_PORT:6379}

open:
    api:
      title: API Document
      version: v1.0.0
      description: Mota API service
      serverUrl: http://localhost:${server.port}
      serverName: server test

jwt:
    expiryHour: 1
    expiryDay: 14
    secretKey: ${JWT_SECRET_KEY}
    refreshKey: ${JWT_REFRESH_KEY}
    resetKey: ${JWT_RESET_KEY}
    verifyKey: ${JWT_VERIFY_KEY}

cloudinary:
  cloud-name: ${CLOUD_NAME}
  api-key: ${CLOUD_KEY}
  api-secret: ${CLOUD_SECRET}
    
vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/vnpay/return
  tmn-code: ${TMN_CODE}
  secret-key: ${SECRET_KEY}
  api-url: ${API_URL}
  ipn-url:  http://localhost:8080/api/vnpay/ipn